

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build && node ./generate-sitemap.cjs"
  publish = "dist"

# Add proxy redirects for Supabase Edge Functions
[[redirects]]
  from = "/api/*"
  to = "https://arseawkxvoqbpvybnttu.supabase.co/functions/v1/:splat"
  status = 200
  force = true

