// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arseawkxvoqbpvybnttu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyc2Vhd2t4dm9xYnB2eWJudHR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzODk2NDQsImV4cCI6MjA1Nzk2NTY0NH0.C6nyKAo6G_XyGSaK7g8NmuefN3YXp84_zKgySmIGAxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);